apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-js
  template:
    metadata:
      labels:
        app: angular-js
    spec:
      containers:
      - name: my-container
        image: ankitha2504/angular-frontend:latest
        ports:
        - containerPort: 4200



   